<?xml version="1.0" encoding="UTF-8" ?>

<project name="dotenv" default="cleanup">

    <target name="cleanup" description="Delete generated folders and files.">
        <delete dir="./.phpunit.cache" includeemptydirs="true" verbose="true" failonerror="false" />
        <delete dir="./coverage-report" includeemptydirs="true" verbose="true" failonerror="false" />
        <delete dir="./vendor" includeemptydirs="true" verbose="true" failonerror="false" />
        <delete>
            <fileset dir="./logs">
                <include name="*.log" />
            </fileset>
        </delete>
    </target>

    <target name="prepare" description="Preparation for release.">
        <delete dir="./.github" includeemptydirs="true" verbose="true" failonerror="false" />
        <delete dir="./logs" includeemptydirs="true" verbose="true" failonerror="false" />
        <delete dir="./tests" includeemptydirs="true" verbose="true" failonerror="false" />
        <delete dir="./zdi" includeemptydirs="true" verbose="true" failonerror="false" />
        <delete file=".gitmodules" />
        <delete>
            <fileset dir=".">
                <include name=".env.example" />
                <include name="build.xml" />
                <include name="docker-compose.example.*" />
                <include name="phpunit.xml" />
                <include name="post-setup.sh" />
            </fileset>
        </delete>
    </target>

</project>
